"""Every link in a published file points at something a public reader can open.

The companion to `tests/test_redaction_rule.py`, and the same shape: a rule about the
*published set*, enforced here so that running it in the archive is a real prediction of what
it will say in the public repository.

**Why it exists.** `tools/published_set.txt` decides which files travel. Nothing decided what
the travelling files were allowed to *point at*, so the README could cite a document that stays
behind and nobody would know until a stranger clicked it. That is not hypothetical: the first
run of this module found **25** such links, eleven of them into `docs/decisions.md` from the
front page of the public repository. A broken link on the landing page is not a cosmetic defect,
it is the reader's first evidence about whether anything else here is maintained.

**It checks two different things, and the second is the one that will fire later.** That a
linked *file* travels is a question about `published_set.txt` and changes when the manifest
does. That a linked *anchor* exists is a question about a heading, and headings get reworded by
people who have no idea anything links to them — so the anchor half is the half that rots
quietly. Both are cheap to check and neither is checkable by eye at this size.

**What it deliberately does not check.** Absolute URLs. Whether <https://hacs.xyz> resolves is
not this repository's business and a test that needs the network to pass is a test that fails on
a train. Bare path mentions in prose and in source comments are also out of scope: they are
citations rather than promises, the same case ADR-007 settled for `#NN` issue references, and
sweeping them would strip real reasoning out of code that is otherwise settled.

The anchor rules mirror GitHub's own slugifier closely enough for the headings this repository
writes: lowercase, drop everything that is not a word character, space or hyphen, then spaces to
hyphens. The em dash in `## ADR-006 — Correct …` is dropped and leaves the two spaces around it
behind, which is why those anchors carry a double hyphen.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from tests.test_redaction_rule import published_files

REPO = Path(__file__).resolve().parent.parent

#: An inline markdown link: a square-bracketed label, then the target in parentheses. Written as
#: a pattern rather than spelled out in this comment, because a literal example here would match
#: itself and this module would report its own documentation as a broken link. Reference-style
#: links are not used anywhere in this tree; if that changes, this is where it has to be noticed
#: rather than silently skipped.
MARKDOWN_LINK = re.compile(r"\[[^\]]*\]\(([^)\s]+)\)")

#: Fenced code blocks, stripped before headings are collected. A `#` inside a shell example is a
#: comment, not a heading, and counting it would invent anchors nothing can link to.
FENCE = re.compile(r"^```.*?^```", re.MULTILINE | re.DOTALL)

HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*$", re.MULTILINE)

#: The file types worth reading. A link inside a `.py` docstring is as clickable on GitHub as one
#: in a `.md`, and `tests/test_redaction_rule.py` has two.
TEXT_SUFFIXES = (".md", ".py", ".yml", ".yaml", ".json", ".txt", ".cfg", ".toml")


def _slug(heading: str) -> str:
    """GitHub's heading anchor, near enough for the headings this repository writes."""
    text = heading.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text)
    return text.replace(" ", "-")


def _anchors(markdown: str) -> set[str]:
    """Exactly the anchors GitHub serves for this document, and no others.

    The suffix rule is the fiddly half. GitHub disambiguates a *repeated* heading by numbering
    the later ones — first occurrence `slug`, then `slug-1`, `slug-2` — so the suffixes have to
    be generated by counting occurrences in document order. Accepting `slug-1` unconditionally
    would be cheaper and would make this guard permissive in exactly the direction that matters:
    a link to `#foo-1` where only `#foo` exists is a broken link, and a check that waves it
    through is worse than no check, because it reports the file as verified.
    """
    body = FENCE.sub("", markdown)
    seen: dict[str, int] = {}
    slugs: set[str] = set()
    for _, heading in HEADING.findall(body):
        base = _slug(heading)
        if not base:
            continue
        n = seen.get(base, 0)
        seen[base] = n + 1
        slugs.add(base if n == 0 else f"{base}-{n}")
    return slugs


def _links(names: list[str]) -> list[tuple[str, str]]:
    found = []
    for name in names:
        if not name.endswith(TEXT_SUFFIXES):
            continue
        text = (REPO / name).read_text(encoding="utf-8")
        found.extend((name, target) for target in MARKDOWN_LINK.findall(text))
    return found


def _relative(links: list[tuple[str, str]]) -> list[tuple[str, str]]:
    return [
        (name, target)
        for name, target in links
        if not target.startswith(("http://", "https://", "mailto:", "tel:", "<"))
    ]


def test_the_sweep_is_not_vacuous():
    """A guard that reads nothing passes for the wrong reason."""
    names = published_files()
    links = _relative(_links(names))
    assert len(names) > 20, f"only {len(names)} published files; the manifest is not being read"
    assert len(links) > 10, (
        f"only {len(links)} relative links found across {len(names)} published files - "
        "either the link pattern stopped matching or the documents lost their cross-references"
    )


def test_every_published_link_points_at_a_published_file():
    """A link out of the published set is a 404 on somebody's first visit."""
    published = set(published_files())
    broken = []
    for name, target in _relative(_links(published_files())):
        path_part = target.split("#", 1)[0]
        if not path_part:
            continue
        resolved = (REPO / name).parent / path_part
        try:
            rel = str(resolved.resolve().relative_to(REPO))
        except ValueError:
            broken.append(f"{name} -> {target} (escapes the repository)")
            continue
        if rel not in published:
            broken.append(f"{name} -> {target}")

    assert not broken, (
        f"{len(broken)} link(s) in the published set point at a file that does not travel.\n"
        "Either publish the target in tools/published_set.txt, or drop the link and keep the\n"
        "prose - ADR-007's rule for #NN references applies to documents too: a live link\n"
        "survives only where the target is something a public reader can actually open.\n  "
        + "\n  ".join(broken)
    )


def test_every_published_anchor_exists_in_the_file_it_points_at():
    """The half that rots quietly: headings get reworded, links do not follow."""
    published = set(published_files())
    cache: dict[str, set[str]] = {}
    broken = []
    for name, target in _relative(_links(published_files())):
        path_part, _, anchor = target.partition("#")
        if not anchor:
            continue
        if path_part:
            rel = str(((REPO / name).parent / path_part).resolve().relative_to(REPO))
        else:
            rel = name
        if rel not in published or not rel.endswith(".md"):
            continue  # the file half is another test's business
        if rel not in cache:
            cache[rel] = _anchors((REPO / rel).read_text(encoding="utf-8"))
        if anchor.lower() not in cache[rel]:
            broken.append(f"{name} -> {target}")

    assert not broken, (
        f"{len(broken)} link(s) name an anchor that no heading in the target produces.\n"
        "Usually a heading was reworded. Fix the link, or the heading, whichever is wrong.\n  "
        + "\n  ".join(broken)
    )


def test_a_repeated_heading_is_numbered_and_a_unique_one_is_not():
    """The suffix rule, pinned. Permissive here means broken links reported as verified.

    Written because the first version of `_anchors` accepted `slug-1` … `slug-5` for *every*
    heading, which would have passed a link to `#what-you-get-1` in a document with one such
    heading - a 404 the guard would have called fine.
    """
    doc = "# Alpha\n\n## Beta\n\ntext\n\n## Beta\n\nmore\n\n## Beta\n"
    assert _anchors(doc) == {"alpha", "beta", "beta-1", "beta-2"}
    assert "alpha-1" not in _anchors(doc), "a unique heading must not accept a numbered anchor"


@pytest.mark.parametrize(
    ("heading", "expected"),
    [
        ("ADR-006 — Correct the power-on intensity reset, and only that one",
         "adr-006--correct-the-power-on-intensity-reset-and-only-that-one"),
        ("Why this file is not called `protocol.md`", "why-this-file-is-not-called-protocolmd"),
        ("Step 2 — Run `tuya-local-key`", "step-2--run-tuya-local-key"),
        ("What you get", "what-you-get"),
    ],
)
def test_the_slugifier_matches_github(heading: str, expected: str):
    """The anchor test is only as good as this, so it is pinned to worked examples.

    Each of these is a heading this repository actually has, with the anchor GitHub actually
    serves for it - checked against the rendered page rather than derived from the rules.
    """
    assert _slug(heading) == expected
