"""Tests for the diagnostics dump - and mostly for the one thing it must never contain.

A diagnostics download is the only artefact this integration produces that is *designed* to
leave the machine it ran on. It is generated by someone whose diffuser is misbehaving and
pasted into a GitHub issue, and the config entry it serialises holds a live `local_key`. So
the assertions here are on the **absence of the values**, not on the shape of the output: a
rewrite that reorganises every key in the dump must still fail if the key comes with it.

Two of the fixtures below are the real thing rather than stand-ins, deliberately:

* **`PollHealth` and `IntensityMemory`** are imported from `coordinator.py`. They carry no
  Home Assistant imports, they are exactly what the dump reads, and using the genuine classes
  means renaming one of their fields breaks this file instead of quietly emitting nulls under
  the old names for ever.
* **the error string is produced by `device.py`**, not transcribed. The leak this file exists
  to catch lives *inside* that module's format string - `f"{self.host}: ..."` - so a
  hand-copied error would be a duplicate that stops matching the source at the first edit,
  and would go on passing while the real thing leaked.
"""

from __future__ import annotations

import json
from datetime import timedelta

import pytest

pytest.importorskip("homeassistant", reason="diagnostics tests need Home Assistant installed")

import tinytuya
from homeassistant.components.diagnostics import REDACTED
from homeassistant.const import CONF_HOST

from custom_components.arozen_eon.const import (
    CONF_DEVICE_ID,
    CONF_LOCAL_KEY,
    CONF_POLL_INTERVAL,
    CONF_PROTOCOL_VERSION,
    TOLERATED_POLL_FAILURES,
)
from custom_components.arozen_eon.coordinator import IntensityMemory, PollHealth
from custom_components.arozen_eon.device import ArozenDevice, ArozenUnreachable
from custom_components.arozen_eon.diagnostics import (
    TO_REDACT,
    async_get_config_entry_diagnostics,
)

#: RFC 5737 TEST-NET-1, the synthetic host the rest of the suite uses. Not a LAN address, so
#: `test_redaction_rule.py` has nothing to say about this file.
HOST = "192.0.2.10"
DEVICE_ID = "test-device-id"
LOCAL_KEY = "0123456789abcdef"

ENTRY_DATA = {
    CONF_HOST: HOST,
    CONF_DEVICE_ID: DEVICE_ID,
    CONF_LOCAL_KEY: LOCAL_KEY,
    CONF_PROTOCOL_VERSION: "3.5",
}

#: A poll interval the options carry but the running coordinator does not, so "which one does
#: the dump report" is a question this fixture can actually answer.
OPTION_POLL_INTERVAL = 300
RUNNING_POLL_INTERVAL = 60

#: A plausible DP set: power on, intensity L4, battery 87, and DP 104 - still unidentified,
#: and the reason the raw set is worth shipping unredacted.
DPS = {"2": True, "3": "L4", "7": True, "101": 87, "103": "kai", "104": "kk"}

#: Every value that must not survive, by the name a failure should call it.
SECRETS = [
    pytest.param(LOCAL_KEY, id="the local key"),
    pytest.param(DEVICE_ID, id="the device id"),
    pytest.param(HOST, id="the host"),
]


def _transport_error(host: str) -> str:
    """The exact string `device.py` raises with, produced by `device.py` itself.

    `_dps_or_raise` reads one attribute off `self` and nothing else, so a stand-in carrying a
    host is enough to make it speak - and far less scaffolding than a fake `tinytuya.Device`
    erected for the sake of one string.
    """

    class _JustAHost:
        pass

    stub = _JustAHost()
    stub.host = host
    with pytest.raises(ArozenUnreachable) as caught:
        ArozenDevice._dps_or_raise(
            stub, {"Error": "Unexpected Payload", "Err": "907"}, "status"
        )
    return str(caught.value)


class FakeCoordinator:
    """Enough of `ArozenCoordinator` for the dump, holding the two real state objects."""

    def __init__(
        self,
        data: dict | None = None,
        poll_interval: int = RUNNING_POLL_INTERVAL,
        last_update_success: bool = True,
    ) -> None:
        #: None is the honest default: a coordinator that has never completed a poll has no
        #: data, and that is the state the dump has to survive.
        self.data = data
        self.last_update_success = last_update_success
        self.update_interval = timedelta(seconds=poll_interval)
        self.health = PollHealth()
        self.intensity = IntensityMemory()


class FakeEntry:
    """A config entry as `diagnostics.py` reads one."""

    def __init__(self, data=None, options=None, coordinator=None) -> None:
        self.entry_id = "test-entry-id"
        self.title = "Arozen EON Pro 2"
        #: The config flow sets the unique id from the device id it has just validated. It is
        #: set here so that the absence tests below also cover that back door: nothing reads
        #: it today, and the moment something does, they fail.
        self.unique_id = DEVICE_ID
        self.data = dict(data if data is not None else ENTRY_DATA)
        self.options = dict(
            options if options is not None else {CONF_POLL_INTERVAL: OPTION_POLL_INTERVAL}
        )
        self.runtime_data = coordinator if coordinator is not None else FakeCoordinator()


async def _dump(entry) -> dict:
    """Build the dump. `hass` is None on purpose - this function has no business touching it,
    and reaching for it would fail here rather than in somebody's Home Assistant."""
    return await async_get_config_entry_diagnostics(None, entry)


@pytest.fixture
def poisoned() -> FakeEntry:
    """An entry in the state that makes the dump dangerous: both error strings carry the host.

    This is not a contrived worst case. It is what an entry looks like after the failure this
    integration actually has - a device that stopped answering - and it is the state a user is
    in at the exact moment they go looking for the Download diagnostics button.
    """
    coordinator = FakeCoordinator(data=dict(DPS))
    error = _transport_error(HOST)
    assert HOST in error, "the fixture is not poisoned, so the tests below prove nothing"

    coordinator.health.failed(error)
    coordinator.intensity.remember("L4")
    coordinator.intensity.restore_failed(error)
    return FakeEntry(coordinator=coordinator)


# -- The thing that must not leak ------------------------------------------------------------


@pytest.mark.parametrize("secret", SECRETS)
async def test_no_connection_value_appears_anywhere_in_the_dump(poisoned, secret):
    """The whole point, asserted over the serialised dump rather than key by key.

    Serialising first is what makes this survive a reorganisation: a value moved into a nested
    structure, a list, or a key nobody thought to check is still a substring of the JSON.
    """
    assert secret not in json.dumps(await _dump(poisoned))


@pytest.mark.parametrize("secret", SECRETS)
async def test_no_eight_character_run_of_a_connection_value_survives(poisoned, secret):
    """Truncation is not redaction; it narrows a search space (docs/captures/README.md).

    A "helpfully" abbreviated key - the first eight characters, to identify which key it was -
    passes the test above and still hands over half the credential. The failure message counts
    the fragments rather than printing one, because a test that leaks a value on its way to
    reporting the leak is its own bug, and CI logs are read more widely than this repository.
    """
    text = json.dumps(await _dump(poisoned))
    runs = [secret[i : i + 8] for i in range(len(secret) - 7)]
    leaked = sum(run in text for run in runs)
    assert leaked == 0, f"{leaked} eight-character fragments of the value survived"


async def test_the_host_is_scrubbed_out_of_the_error_strings(poisoned):
    """The leak `async_redact_data` cannot see, and the only reason `_scrub` exists.

    `device.py` prefixes every failure with the host, so the most useful field in the dump is
    also the one carrying a LAN address in free text. Redacting by key never touches it.
    """
    dump = await _dump(poisoned)
    for last_error in (
        dump["coordinator"]["health"]["last_error"],
        dump["coordinator"]["intensity"]["last_error"],
    ):
        assert REDACTED in last_error
        # And the rest of the message survived: a scrub that returned the placeholder alone
        # would pass every absence test above and throw away the diagnosis.
        assert "907" in last_error


async def test_the_credential_keys_are_reported_as_present_and_redacted(poisoned):
    """Present, not absent. "The key is set but wrong" and "the key is missing" are different
    bugs, and dropping the keys entirely makes the dump unable to tell them apart."""
    data = (await _dump(poisoned))["entry"]["data"]
    for key in TO_REDACT:
        assert data[key] == REDACTED


async def test_a_blank_connection_value_does_not_shred_the_dump():
    """`"anything".replace("", REDACTED)` inserts the placeholder between every character.

    A blank host is not reachable through the config flow, which validates by connecting, but
    a hand-edited `.storage` file reaches it fine - and the result would be a dump whose every
    string is confetti, including the error the reporter came to ask about.
    """
    coordinator = FakeCoordinator()
    coordinator.health.failed("the device stopped answering")
    entry = FakeEntry(data={**ENTRY_DATA, CONF_HOST: ""}, coordinator=coordinator)

    dump = await _dump(entry)
    assert dump["coordinator"]["health"]["last_error"] == "the device stopped answering"


# -- What has to be in it to be worth downloading ---------------------------------------------


async def test_the_settings_a_support_conversation_needs_are_left_alone(poisoned):
    """The guard against redacting everything, which passes every absence test perfectly and
    produces a file with nothing in it. These two are what a wrong-version report turns on."""
    dump = await _dump(poisoned)
    assert dump["entry"]["data"][CONF_PROTOCOL_VERSION] == "3.5"
    assert dump["entry"]["options"][CONF_POLL_INTERVAL] == OPTION_POLL_INTERVAL


async def test_the_raw_datapoints_are_included_unredacted(poisoned):
    """Numbered datapoints and their values: no identifier, and the most useful thing here."""
    assert (await _dump(poisoned))["dps"] == DPS


async def test_the_datapoints_are_copied_rather_than_handed_out_live(poisoned):
    """Home Assistant awaits three more coroutines between building this dump and serialising
    it, so a poll can land in between. A live reference would let the dump change underneath
    the encoder; the copy is what makes it a snapshot of the moment it was asked for."""
    dump = await _dump(poisoned)
    assert dump["dps"] is not poisoned.runtime_data.data


async def test_the_health_counters_are_included(poisoned):
    health = (await _dump(poisoned))["coordinator"]["health"]
    assert health["total"] == 1
    assert health["consecutive"] == 1
    assert health["tolerated"] == TOLERATED_POLL_FAILURES
    assert health["last_failure"] is not None


async def test_the_intensity_memory_is_included(poisoned):
    memory = (await _dump(poisoned))["coordinator"]["intensity"]
    assert memory["wanted"] == "L4"
    assert memory["restored"] == 0
    assert memory["failures"] == 1
    assert memory["unconfirmed"] is False


async def test_last_update_success_is_included():
    entry = FakeEntry(coordinator=FakeCoordinator(last_update_success=False))
    assert (await _dump(entry))["coordinator"]["last_update_success"] is False


async def test_the_interval_reported_is_the_one_the_coordinator_is_running_at():
    """Not the one in the options. Applying a changed interval means a reload, so the two
    disagreeing is the finding - an option that was saved and never took effect. Reporting the
    option instead would show the setting the user already knows they chose."""
    dump = await _dump(FakeEntry())
    assert dump["coordinator"]["update_interval_s"] == RUNNING_POLL_INTERVAL
    assert dump["entry"]["options"][CONF_POLL_INTERVAL] == OPTION_POLL_INTERVAL


async def test_the_imported_tinytuya_version_is_reported(poisoned):
    """The manifest pins it (#48) and Home Assistant attaches the manifest; this is the
    version that actually got imported, which is the half that can differ."""
    assert (await _dump(poisoned))["tinytuya_version"] == tinytuya.__version__


# -- The states it has to survive --------------------------------------------------------------


async def test_the_dump_survives_a_device_that_never_answered():
    """The most likely install to need diagnostics is the one that has never worked: a wrong
    key or a wrong protocol version means `coordinator.data` is still None."""
    dump = await _dump(FakeEntry(coordinator=FakeCoordinator(data=None)))
    assert dump["dps"] is None
    assert dump["coordinator"]["health"]["last_error"] is None
    assert dump["coordinator"]["intensity"]["last_error"] is None
    assert json.dumps(dump)


async def test_the_dump_is_plain_json_with_no_custom_encoder(poisoned):
    """Home Assistant serialises with `ExtendedJSONEncoder`, which would quietly rescue a
    `timedelta` or a `datetime` into a rendering nobody chose. Every value here is a primitive
    on purpose, so the dump reads the same in an issue as it does under a plain encoder."""
    assert json.dumps(await _dump(poisoned))
